steps:

# This steps clone the repository into GCP
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://PatrickVibild:holadontsteal1@github.com/PatrickVibild/n1scrapper']

#This step creates a container and leave it on CloudBuilds repository.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'gcr.io/abiding-robot-255320/n1scrapper:$SHORT_SHA', '.']

#Adds the container to Google container registry as an artefact
- name: 'gcr.io/cloud-builders/docker'
  id: Container push
  args: ['push', 'gcr.io/abiding-robot-255320/n1scrapper:$SHORT_SHA']
